-- CREATE TABLE t (
-- id SERIAL PRIMARY KEY,
-- name VARCHAR NOT NULL,
-- price NUMERIC(10,2) DEFAULT 0
-- );

CREATE TABLE fakeTable (
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
price NUMERIC(10,2) DEFAULT 0
);